[package]
name = "solaris-example"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
ethabi-derive = { git = "https://github.com/tomusdrw/ethabi.git"}
ethabi-contract = { git = "https://github.com/tomusdrw/ethabi.git"}
# ethabi = "4.2"
# ethabi-contract = "4.0"
# ethabi-derive = "4.2"
solaris = { path = "../solaris", version = "0.1" }
