[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
# ethabi = "4.2"
# ethabi-derive = "4.2"
# ethabi-contract = "4.0"
ethabi = { git = "https://github.com/tomusdrw/ethabi.git" }
ethabi-derive = { git = "https://github.com/tomusdrw/ethabi.git"}
ethabi-contract = { git = "https://github.com/tomusdrw/ethabi.git"}
ethcore = { git = "https://github.com/paritytech/parity.git" }
