[package]
name = "solaris"
version = "0.1.0"
authors = ["Tomasz Drwięga <tomusdrw@gmail.com>"]

[dependencies]
# ethabi = "4.2"
# ethabi-derive = "4.2"
# ethabi-contract = "4.0"
ethabi = { path = "../../ethabi/ethabi"}
ethabi-derive = { path = "../../ethabi/derive"}
ethabi-contract = { path = "../../ethabi/contract"}
ethcore = { git = "https://github.com/paritytech/parity.git" }
